name: net-disk

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            set -e
            cd /root/net-disk
            git pull origin master
            nvm use 20.11.0
            npm install || exit 1
            npm run build || exit 1
            mv dist/* /usr/share/nginx/html/
            systemctl restart nginx
